"""The lines an NPC says in chat right after a quest is accepted or turned in.

Writes addons/Spoken_Quests/FollowupLines.lua, which the addon reads to recognise those lines
as they arrive in /say or /yell and voice them.

Which lines they are, and who says them, is tts_cli/followup.py: the corpus reads the same
extraction to voice them, and its docstring explains the rules. The one rule that is this
file's alone: a quest with several enders or givers is written with no speaker, since the
addon rejects a line from anybody but the recorded speaker and picking one would silence the
line at every other. The corpus voices it in each of them instead.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tts_cli.followup import collect  # noqa: E402
from tts_cli.sql_queries import make_connection  # noqa: E402

DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "..", "..", "addons", "Spoken_Quests", "FollowupLines.lua")


def lua_string(text):
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32 or ord(ch) == 127:
            out.append(f"\\{ord(ch):03d}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def render(result):
    out = [
        "setfenv(1, VoiceOver)",
        "",
        "-- Generated by pipelines/quests/tools/export_followup_lines.py; do not edit by hand.",
        "-- The world DB's quest start/end scripts make NPCs speak in chat after a quest is",
        "-- accepted or turned in. The client never sees those lines as quest text, so this is",
        "-- how the addon recognises them. speaker is a creature entry, absent when unresolved.",
        "-- step is the script step a line is one outcome of: once one is heard, the rest of",
        "-- its step never will be.",
        "FollowupLines = {",
    ]
    for event in ("end", "start"):
        out.append(f'    [{lua_string(event)}] = {{')
        for quest, (title, lines) in sorted(result[event].items()):
            comment = " ".join((title or "").split())
            out.append(f"        [{quest}] = {{ -- {comment}")
            for line in lines:
                fields = [f"id = {line['id']}", f"step = {line['step']}"]
                if line["speaker"] is not None:
                    fields.append(f"speaker = {line['speaker']}")
                fields += [f"delay = {line['delay']}", f"chat = {lua_string(line['chat'])}",
                           f"male = {lua_string(line['male'])}"]
                # Absent when it is the male text, which it is for every line today: the
                # copy was a third of the file every login parses, and a second render of
                # the same string on every armed chat message.
                if line["female"] != line["male"]:
                    fields.append(f"female = {lua_string(line['female'])}")
                out.append("            { " + ", ".join(fields) + " },")
            out.append("        },")
        out.append("    },")
    out.append("}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()

    result, stats = collect(make_connection())
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(result))

    print(f"wrote {os.path.normpath(args.out)}")
    for event, quests in result.items():
        count = sum(len(lines) for _, lines in quests.values())
        how, many = stats[event]
        print(f"  {event}: {count} lines across {len(quests)} quests")
        for (via, resolved), n in sorted(how.items()):
            print(f"    speaker via {via}: {n} {'resolved' if resolved else 'nil'}")
        if many:
            print(f"    several possible speakers, left unset: {', '.join(map(str, many))}")
